### ISSUE TITLE
Filtering and Sorting of DAO Members

### ISSUE THREAD

**Issue by djstrikanova** [effectai/effect-dashboard#106]
On the https://dao.effect.network/dao page, it would be useful to be able to filter between the different members. For example, to see who has the most voting power, who joined the latest. Who has the most staked EFX and NFX.

**Comment by Wholesomebruh** [comment]
@djstrikanova , Is it still open to work?

**Comment by jeisses** [comment]
Hi @Wholesomebruh 
This is issues is open to be worked on. Feel free to pick it up and ask any questions you have regarding the code base and implementation

**Comment by Wholesomebruh** [comment]
Hey @jeisses , thanks for confirming. Please guide me how can I produce the https://dao.effect.network/dao page in local development.

**Comment by jeisses** [comment]
You will need to have npm installed and then download dependencies:

```
npm install 
```

After that you can run a local development server with hotreload:

```
npm run dev
```

The port will be printed to the console

**Comment by Wholesomebruh** [comment]
I cloned the repository and ran 
```bash
npm install
```
I am getting this error:
![image](https://github.com/effectai/effect-dao/assets/109906215/7f53d90b-f5c5-4e2b-b431-87b795c05600)

**Comment by jeisses** [comment]
You will need to use version 14 of NodeJS to run it. There is a tool called `nvm` that can be used to switch the version of NodeJS, I recommend that instead of changing your sytem node installation

**Comment by Wholesomebruh** [comment]
Thanks for helping . As of now , package installation is working properly with `npm install` but on `npm run dev` it is still giving same node-sass issue :
```bash
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):                                             friendly-errors 04:39:10
Error: ENOENT: no such file or directory, scandir 'E:\effect-dao\node_modules\node-sass\vendor'
    at Object.readdirSync (fs.js:1048:3)
    at Object.getInstalledBinaries (E:\effect-dao\node_modules\node-sass\lib\extensions.js:133:13)
    at foundBinariesList (E:\effect-dao\node_modules\node-sass\lib\errors.js:20:15)
    at foundBinaries (E:\effect-dao\node_modules\node-sass\lib\errors.js:15:5)
    at Object.module.exports.missingBinary (E:\effect-dao\node_modules\node-sass\lib\errors.js:45:5)
    at module.exports (E:\effect-dao\node_modules\node-sass\lib\binding.js:15:30)
    at Object.<anonymous> (E:\effect-dao\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (internal/modules/cjs/loader.js:1114:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Module.load (internal/modules/cjs/loader.js:979:32)
    at Function.Module._load (internal/modules/cjs/loader.js:819:12)
    at Module.require (internal/modules/cjs/loader.js:1003:19)
    at require (internal/modules/cjs/helpers.js:107:18)
    at getDefaultSassImplementation (E:\effect-dao\node_modules\sass-loader\dist\utils.js:43:10)
    at getSassImplementation (E:\effect-dao\node_modules\sass-loader\dist\utils.js:57:30)
    at Object.loader (E:\effect-dao\node_modules\sass-loader\dist\index.js:34:59)
    
    I will try few things and update you on this.

**Comment by optimystical** [comment]
Opened a focused PR for this: https://github.com/effectai/effect-dao/pull/230

**Comment by Karry2019web** [comment]
👋 I'd like to work on this. I'll add filtering and sorting capabilities for DAO members - filtering by voting power, stake amount, join date, and sorting by various criteria.

**Comment by Karry2019web** [comment]
/attempt

PR created: https://github.com/effectai/effect-dao/pull/231
